Mobile version skeleton
Estherstarr/personalPortfolio pull request #1
Opened 2022-02-17 14:58 UTC by Estherstarr

Mobile Portfolio Version Skeleton
- Creat a sample for my Mobile Portfolio using index.html and CSS
- Add  .gitignore to ignore node_modules and test.md files
- Include Linters for HTML/CSS
-

2022-02-17 16:41 UTC, thecodechaser requested changes
## Hi @Estherstarr 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
-  Clean code ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 16:41 UTC, thecodechaser commented on index.html
> +              </button>
- [ ] You did a very great job on the design but there is a little issue. You are supposed to stick to the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) as much as possible. Your hamburger icon should be on the right of the screen but currently, it is appearing in the center. Please place your hamburger icon right side of the screen and make sure it matches the design. 

Your design

![Screenshot (153)](https://user-images.githubusercontent.com/83803414/154527409-5b45fac5-fa21-4e2a-bbff-fa2cc425bcfd.png)

Figma design

![Screenshot (152)](https://user-images.githubusercontent.com/83803414/154527443-02fb194c-b0d0-4084-8a18-bbc564374f2e.png)

2022-02-17 17:02 UTC, Estherstarr commented
![Screenshot from 2022-02-17 17-52-19](https://user-images.githubusercontent.com/60798978/154531947-081a7720-5751-4eac-a4b2-4dc70ad137de.png)

@thecodechaser This image is how it displays on my browser. The hamburger is on the right.  I'm a bit confused about what to do next

2022-02-17 17:19 UTC, thecodechaser commented
@Estherstarr The screenshot you shared is the desktop version, You are currently seeing your webpage on desktop screen
Use inspect elements to switch to mobile screen and you will see the icon is in the center

2022-02-17 17:37 UTC, Estherstarr commented
@thecodechaser what do I need to do. Because the instruction asked to use flexbox. Should I use media queries? I'm stuck can you give me hints on how to go about this error

2022-02-17 17:45 UTC, thecodechaser commented
@Estherstarr Hello there, You go with one of the following solutions
- Apply `margin-left` to your navbar accordingly so it matches the design
- You can use `position: absolute;` for your hamburger button and apply top and right properties accordingly so it matches the design.

2022-02-18 01:06 UTC, Estherstarr commented
Thank you @thecodechaser 

The requested changes made
-The hamburger  icon is on the right side of the screen with or without inspect

2022-02-18 10:15 UTC, elmar8287 approved these changes
Hi, @Estherstarr.

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

## Please, before merging consider my OPTIONAL suggestion in the comments under the review 👍 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 10:15 UTC, elmar8287 commented on README.md
> +
- [ ] [OPTIONAL] As it was not marked by the previous review, this is marked as an optional suggestion: 
- Please, could you remove the doubling of information in README file 👍

2022-02-18 10:15 UTC, elmar8287 commented on index.html
> +
- [ ] [OPTIONAL] As it was not marked by the previous review, this is marked as an optional suggestion: 
- Please, could you put your toolbar section into the `header` tag - it is for considering HTML semantic structure 👍

2022-02-18 10:15 UTC, elmar8287 commented on index.html
> +    </section>
- [ ] [OPTIONAL] As it was not marked by the previous review, this is marked as an optional suggestion: 
- Please, consider closing the `body` and `HTML` tags 👍

2022-02-18 11:57 UTC, Estherstarr commented
@elmar8287 Thank you for the review 
Optional changes 
 - closing the body and HTML tags
 - Add toolbar section into the header tag 
 -  Remove the doubling of information in README file

2022-02-18 14:44 UTC, merged